name: Release

on:
  push:
    tags: ['*']

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          path: dist/build

      - name: Setup Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 20.14
      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
        with:
          php-version: 8.2
          extensions: gmp
          tools: composer:v2
      - name: Build backend
        run: |
          cd dist/build/backend
          composer install --no-dev --optimize-autoloader --no-interaction
          bin/doctrine orm:generate-proxies
          composer openapi
        env:
          NEUCORE_APP_ENV: prod
          NEUCORE_DATABASE_URL: 'mysql://user:@127.0.0.1/db?serverVersion=10.5.22-MariaDB-1:10.5.22+maria~ubu2004'
      - name: Generate OpenAPI client
        run: |
          cd dist/build/frontend
          ./openapi.sh
      - name: Build OpenAPI client
        run: |
          cd dist/build/frontend/neucore-js-client
          npm install
          npm run build
      - name: Build frontend
        run: |
          cd dist/build/frontend
          npm ci
          npm run build
      - name: Get the version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Create archive
        run: |
          dist/build/setup/dist-collect-files.sh
          cd dist
          tar -czf neucore-${{ env.RELEASE_VERSION }}.tar.gz neucore
          sha256sum neucore-${{ env.RELEASE_VERSION }}.tar.gz > neucore-${{ env.RELEASE_VERSION }}.sha256

      - name: GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            dist/neucore-${{ env.RELEASE_VERSION }}.tar.gz
            dist/neucore-${{ env.RELEASE_VERSION }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        if: ${{ github.repository_owner == 'tkhamez' }}
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      - name: Set up Docker Buildx
        if: ${{ github.repository_owner == 'tkhamez' }}
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Build and publish Docker image
        if: ${{ github.repository_owner == 'tkhamez' }}
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u tkhamez --password-stdin
          docker buildx build --platform linux/amd64,linux/arm64 -f dist/build/setup/Dockerfile --no-cache -t tkhamez/neucore:${{ env.RELEASE_VERSION }} -t tkhamez/neucore:latest --push dist
          docker logout
